import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import {getDatabase,ref,push,set,remove,onValue,serverTimestamp,query,orderByChild,equalTo,get} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-database.js';
const firebaseConfig={apiKey:'AIzaSyBWvP09xGRux29JoEZb1k26F545lMYE98A',authDomain:'chat-privado-b263d.firebaseapp.com',projectId:'chat-privado-b263d',databaseURL:'https://chat-privado-b263d-default-rtdb.firebaseio.com',storageBucket:'chat-privado-b263d.firebasestorage.app',messagingSenderId:'103339133634',appId:'1:103339133634:web:59277533c9d3b9b3ab095b'};
// Correct API key used by the project.
const app=initializeApp({...firebaseConfig,apiKey:'AIzaSyBWvP09xGRux29JoEZb1k26F545lMYE98A'}),auth=getAuth(app),db=getDatabase(app);const $=id=>document.getElementById(id);
const emojis=['😀','😂','😍','🥰','😘','😭','😎','🤩','😡','👍','👎','❤️','💚','💙','💯','🔥','🎉','🤣','😊','😉','😢','😮','🤔','🙏','👏','🙌','✨','⚽','🎮','🚀','👋','💬'];
let currentContact=null,stopContacts=null,stopMessages=null,replyTo=null,swipeStartX=0,swipeEl=null,pressTimer=null;
function errText(e){const c=e?.code||'';if(c.includes('invalid-credential'))return'Correo o contraseña incorrectos';if(c.includes('email-already-in-use'))return'Ese correo ya tiene una cuenta';if(c.includes('weak-password'))return'La contraseña debe tener al menos 6 caracteres';return e?.message||'Ocurrió un error'}
function showErr(x){$('err').textContent=typeof x==='string'?x:errText(x)}
function chatId(a,b){return [a,b].sort().join('_')}
function nameFor(user){return user?.name||user?.email?.split('@')[0]||'Contacto'}
function initials(n){return (n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
async function login(){const email=$('email').value.trim(),pass=$('pass').value;if(!email||!pass)return showErr('Escribe tu correo y contraseña');showErr('');$('login').disabled=true;$('login').textContent='Entrando…';try{await signInWithEmailAndPassword(auth,email,pass)}catch(e){showErr(e);$('login').disabled=false;$('login').textContent='Entrar'}}
async function register(){const email=$('email').value.trim(),pass=$('pass').value;if(!email||!pass)return showErr('Escribe tu correo y una contraseña');showErr('');$('register').disabled=true;$('register').textContent='Creando…';try{await createUserWithEmailAndPassword(auth,email,pass)}catch(e){showErr(e);$('register').disabled=false;$('register').textContent='Crear cuenta'}}
function showView(v){$('auth').classList.toggle('hidden',v!=='auth');$('contactsView').classList.toggle('hidden',v!=='contacts');$('chatView').classList.toggle('hidden',v!=='chat')}
function setupEmoji(){ $('emojiPanel').innerHTML=emojis.map(e=>`<button type="button">${e}</button>`).join('');$('emoji').onclick=()=>$('emojiPanel').classList.toggle('hidden');$('emojiPanel').onclick=e=>{if(e.target.tagName==='BUTTON'){const t=$('text'),s=t.selectionStart??t.value.length;t.value=t.value.slice(0,s)+e.target.textContent+t.value.slice(t.selectionEnd??s);t.selectionStart=t.selectionEnd=s+e.target.textContent.length;t.focus()}}}
function contactRefs(){return ref(db,'contacts/'+auth.currentUser.uid)}
function loadContacts(){if(stopContacts)stopContacts();stopContacts=onValue(contactRefs(),snap=>{const box=$('contacts');box.innerHTML='';let n=0;snap.forEach(c=>{const u=c.val()||{};n++;const el=document.createElement('div');el.className='contact';const av=document.createElement('div');av.className='avatar';av.textContent=initials(nameFor(u));const info=document.createElement('div');info.className='info';const nm=document.createElement('div');nm.className='name';nm.textContent=nameFor(u);const em=document.createElement('div');em.className='email';em.textContent=u.email||'';info.append(nm,em);el.append(av,info);el.onclick=()=>openChat(c.key,u);box.appendChild(el)});if(!n)box.innerHTML='<div class="empty">👥<br><br>No tienes contactos todavía.<br>Toca <b>＋</b> para agregar uno.</div>'},e=>{$('contacts').innerHTML='<div class="empty">⚠️<br>'+e.message+'</div>'})}
function openAdd(){ $('contactEmail').value='';$('contactErr').textContent='';$('addModal').classList.remove('hidden');setTimeout(()=>$('contactEmail').focus(),50)}
function closeAdd(){$('addModal').classList.add('hidden')}
async function addContact(){const email=$('contactEmail').value.trim().toLowerCase();$('contactErr').textContent='';if(!email)return $('contactErr').textContent='Escribe un correo electrónico';if(email===auth.currentUser.email.toLowerCase())return $('contactErr').textContent='No puedes agregarte a ti mismo';$('confirmAdd').disabled=true;$('confirmAdd').textContent='Buscando…';try{const snap=await get(query(ref(db,'users'),orderByChild('email'),equalTo(email)));if(!snap.exists()){return $('contactErr').textContent='No encontramos una cuenta con ese correo'}let found=null;snap.forEach(c=>{found={uid:c.key,...(c.val()||{})}});if(!found)return;$('confirmAdd').textContent='Agregando…';await set(ref(db,'contacts/'+auth.currentUser.uid+'/'+found.uid),{email:found.email,name:nameFor(found)});await set(ref(db,'contacts/'+found.uid+'/'+auth.currentUser.uid),{email:auth.currentUser.email,name:nameFor(auth.currentUser)});closeAdd();toast('Contacto agregado ✓')}catch(e){$('contactErr').textContent=e?.message||'No se pudo agregar el contacto'}finally{$('confirmAdd').disabled=false;$('confirmAdd').textContent='Agregar'}}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function openChat(uid,u){currentContact={uid,...u};$('chatAvatar').textContent=initials(nameFor(u));$('chatName').textContent=nameFor(u);showView('chat');replyTo=null;updateReplyBar();listenMessages()}
function listenMessages(){if(stopMessages)stopMessages();const id=chatId(auth.currentUser.uid,currentContact.uid);stopMessages=onValue(query(ref(db,'chats/'+id+'/messages'),orderByChild('time')),snap=>{const box=$('messages');box.innerHTML='';snap.forEach(c=>renderMessage(c.key,c.val()||{},box));box.scrollTop=box.scrollHeight},e=>{$('messages').innerHTML='<div class="empty">⚠️<br>'+e.message+'</div>'})}
function renderMessage(key,m,box){const mine=m.uid===auth.currentUser.uid,wrap=document.createElement('div');wrap.className='bubblewrap '+(mine?'mine':'theirs');wrap.dataset.key=key;wrap.dataset.text=m.text||'';const bubble=document.createElement('div');bubble.className='bubble';if(m.replyTo?.text){const q=document.createElement('div');q.className='replyquote';q.textContent='↩ '+m.replyTo.text;bubble.appendChild(q)}const span=document.createElement('span');span.textContent=m.text||'';bubble.appendChild(span);const meta=document.createElement('span');meta.className='meta';meta.textContent=m.time?new Date(m.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'…';if(mine){const ck=document.createElement('span');ck.className='checks';ck.textContent=' ✓✓';meta.appendChild(ck)}bubble.appendChild(meta);const actions=document.createElement('div');actions.className='swipe-actions';const rb=document.createElement('button');rb.textContent='↩ Responder';rb.onclick=()=>{setReply(key,m);wrap.style.transform='translateX(0)';actions.style.display='none'};actions.appendChild(rb);wrap.append(bubble,actions);attachGesture(wrap);box.appendChild(wrap)}
function setReply(key,m){replyTo={key,text:m.text||'',uid:m.uid};updateReplyBar();$('text').focus()}
function updateReplyBar(){if(replyTo){$('replyBar').classList.remove('hidden');$('replyText').textContent='↩ '+replyTo.text}else{$('replyBar').classList.add('hidden');$('replyText').textContent=''}}
function attachGesture(el){el.addEventListener('touchstart',e=>{swipeStartX=e.touches[0].clientX;swipeEl=el},{passive:true});el.addEventListener('touchmove',e=>{if(swipeEl!==el)return;const dx=e.touches[0].clientX-swipeStartX;if(dx<0)el.style.transform=`translateX(${Math.max(dx,-115)}px)`},{passive:true});el.addEventListener('touchend',()=>{const dx=parseFloat((el.style.transform||'translateX(0)').match(/-?[\d.]+/)?.[0]||0);if(dx<-55){el.querySelector('.swipe-actions').style.display='flex'}else{el.style.transform='translateX(0)';el.querySelector('.swipe-actions').style.display='none'}swipeEl=null})}
function setupLongPress(){document.addEventListener('touchstart',e=>{const w=e.target.closest('.bubblewrap');if(!w)return;pressTimer=setTimeout(()=>showContext(w,e.changedTouches[0].clientX,e.changedTouches[0].clientY),600)},{passive:true});document.addEventListener('touchend',()=>clearTimeout(pressTimer));document.addEventListener('touchmove',()=>clearTimeout(pressTimer),{passive:true})}
function showContext(w,x,y){document.querySelector('.context')?.remove();const menu=document.createElement('div');menu.className='context';menu.style.left=Math.min(x,innerWidth-155)+'px';menu.style.top=Math.min(y,innerHeight-90)+'px';const del=document.createElement('button');del.textContent='🗑️ Eliminar';del.onclick=()=>deleteMessage(w.dataset.key);menu.append(del);document.body.appendChild(menu);setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0)}
async function deleteMessage(key){const id=chatId(auth.currentUser.uid,currentContact.uid);if(!confirm('¿Eliminar este mensaje?'))return;try{await remove(ref(db,'chats/'+id+'/messages/'+key))}catch(e){alert('No se pudo eliminar: '+e.message)}}
$('login').onclick=login;$('register').onclick=register;$('pass').onkeydown=e=>{if(e.key==='Enter')login()};$('addContact').onclick=openAdd;$('cancelAdd').onclick=closeAdd;$('confirmAdd').onclick=addContact;$('contactEmail').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addContact()}};$('addModal').onclick=e=>{if(e.target.id==='addModal')closeAdd()};$('back').onclick=()=>{if(stopMessages){stopMessages();stopMessages=null}currentContact=null;showView('contacts');loadContacts()};$('cancelReply').onclick=()=>{replyTo=null;updateReplyBar()};$('logoutContacts').onclick=()=>signOut(auth);
$('composer').onsubmit=async e=>{e.preventDefault();const text=$('text').value.trim();if(!text||!currentContact)return;const id=chatId(auth.currentUser.uid,currentContact.uid);const data={uid:auth.currentUser.uid,text,time:serverTimestamp(),replyTo:replyTo?{key:replyTo.key||'',text:replyTo.text||'',uid:replyTo.uid||''}:null};try{await push(ref(db,'chats/'+id+'/messages'),data);$('text').value='';$('text').style.height='44px';replyTo=null;updateReplyBar();$('emojiPanel').classList.add('hidden');$('text').focus()}catch(e){alert('No se pudo enviar: '+e.message)}};
$('text').oninput=()=>{const t=$('text');t.style.height='44px';t.style.height=Math.min(t.scrollHeight,120)+'px'};$('text').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}};
setupEmoji();setupLongPress();onAuthStateChanged(auth,async user=>{if(!user){showView('auth');return}showView('contacts');loadContacts();try{await set(ref(db,'users/'+user.uid),{email:user.email,name:user.email.split('@')[0]})}catch(e){console.warn(e)}});
