import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import {getDatabase,ref,push,onValue,serverTimestamp,query,orderByChild} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-database.js';
const firebaseConfig={apiKey:'AIzaSyBWvP09xGRux29JoEZb1k26F545lMYE98A',authDomain:'chat-privado-b263d.firebaseapp.com',projectId:'chat-privado-b263d',databaseURL:'https://chat-privado-b263d-default-rtdb.firebaseio.com',storageBucket:'chat-privado-b263d.firebasestorage.app',messagingSenderId:'103339133634',appId:'1:103339133634:web:59277533c9d3b9b3ab095b'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);const $=id=>document.getElementById(id);const emojis=['😀','😂','😍','🥰','😘','😭','😎','🤩','😡','👍','👎','❤️','💚','💙','💯','🔥','🎉','🤣','😊','😉','😢','😮','🤔','🙏','👏','🙌','✨','⚽','🎮','🚀','👋','💬'];
$('emojiPanel').innerHTML=emojis.map(e=>`<button type="button">${e}</button>`).join('');$('emoji').onclick=()=>$('emojiPanel').classList.toggle('hidden');$('emojiPanel').onclick=e=>{if(e.target.tagName==='BUTTON'){const t=$('text');t.value+=e.target.textContent;t.focus();}};
function showErr(e){$('err').textContent=e?.code?.includes('auth/invalid-credential')?'Correo o contraseña incorrectos':e?.code?.includes('auth/email-already-in-use')?'Ese correo ya tiene una cuenta':e?.code?.includes('auth/weak-password')?'La contraseña debe tener al menos 6 caracteres':e?.message||'Ocurrió un error';}
async function doLogin(){const email=$('email').value.trim(),pass=$('pass').value;if(!email||!pass){showErr('Escribe tu correo y contraseña');return}showErr('');$('login').disabled=true;$('login').textContent='Entrando…';try{await signInWithEmailAndPassword(auth,email,pass)}catch(e){showErr(e);$('login').disabled=false;$('login').textContent='Entrar'}}async function doRegister(){const email=$('email').value.trim(),pass=$('pass').value;if(!email||!pass){showErr('Escribe tu correo y una contraseña');return}showErr('');$('register').disabled=true;$('register').textContent='Creando…';try{await createUserWithEmailAndPassword(auth,email,pass)}catch(e){showErr(e);$('register').disabled=false;$('register').textContent='Crear cuenta'}}$('login').addEventListener('click',doLogin);$('register').addEventListener('click',doRegister);$('pass').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();doLogin()}});
$('composer').onsubmit=async e=>{e.preventDefault();const text=$('text').value.trim();if(!text||!auth.currentUser)return;try{await push(ref(db,'messages'),{uid:auth.currentUser.uid,text,time:serverTimestamp()});$('text').value='';$('emojiPanel').classList.add('hidden');$('text').focus()}catch(e){alert('No se pudo enviar: '+e.message)}};
$('text').addEventListener('input',()=>{const t=$('text');t.style.height='44px';t.style.height=Math.min(t.scrollHeight,120)+'px'});$('text').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}});
let started=false;onAuthStateChanged(auth,user=>{if(user){$('auth').classList.add('hidden');$('chat').classList.remove('hidden');if(!started){started=true;listen()}}else{$('chat').classList.add('hidden');$('auth').classList.remove('hidden')}});
function listen(){onValue(query(ref(db,'messages'),orderByChild('time')),snap=>{const box=$('messages');box.innerHTML='';let count=0;snap.forEach(c=>{count++;const m=c.val()||{},mine=m.uid===auth.currentUser?.uid;const b=document.createElement('div');b.className='bubble '+(mine?'mine':'theirs');const d=m.time?new Date(m.time):new Date();const time=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});b.innerHTML=`<span></span><span class="meta">${time}${mine?'<span class="checks"> ✓✓</span>':''}</span>`;b.firstElementChild.textContent=m.text||'';box.appendChild(b)});if(!count)box.innerHTML='<div class="empty">🔒<br><br>Esta conversación es privada.<br>Envía el primer mensaje.</div>';box.scrollTop=box.scrollHeight},e=>{ $('messages').innerHTML='<div class="empty">⚠️<br><br>'+e.message+'</div>'})}
