import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import { getDatabase, ref, push, onValue, serverTimestamp, query, orderByChild } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-database.js';

const firebaseConfig={apiKey:'AIzaSyBWvP09xGRux29JoEZb1k26F545lMYE98A',authDomain:'chat-privado-b263d.firebaseapp.com',projectId:'chat-privado-b263d',storageBucket:'chat-privado-b263d.firebasestorage.app',messagingSenderId:'103339133634',appId:'1:103339133634:web:59277533c9d3b9b3ab095b',databaseURL:'https://chat-privado-b263d-default-rtdb.firebaseio.com/'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
const $=id=>document.getElementById(id); const authMsg=$('authMsg');
function showMsg(t,ok=false){authMsg.textContent=t;authMsg.className='msg'+(ok?' ok':'')}
function friendly(e){const c=e?.code||'';const m={ 'auth/invalid-credential':'Correo o contraseña incorrectos.','auth/invalid-email':'El correo no es válido.','auth/email-already-in-use':'Ese correo ya tiene una cuenta.','auth/weak-password':'La contraseña debe tener al menos 6 caracteres.','auth/network-request-failed':'No hay conexión a Internet.','auth/too-many-requests':'Demasiados intentos. Espera un momento.','permission-denied':'Firebase no permite acceder a la base de datos. Revisa las reglas de Realtime Database.'};return m[c]||e?.message||'Ocurrió un error.'}
$('loginBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value; if(!email||!password)return showMsg('Completa correo y contraseña.');showMsg('Entrando...',true);try{await signInWithEmailAndPassword(auth,email,password);showMsg('');}catch(e){showMsg(friendly(e))}};
$('registerBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return showMsg('Completa correo y contraseña.');showMsg('Creando cuenta...',true);try{await createUserWithEmailAndPassword(auth,email,password);showMsg('Cuenta creada.',true)}catch(e){showMsg(friendly(e))}};
$('logoutBtn').onclick=()=>signOut(auth);
let unsubscribe=null;
onAuthStateChanged(auth,user=>{if(user){$('home').classList.add('hidden');$('chat').classList.remove('hidden');listen(user)}else{$('chat').classList.add('hidden');$('home').classList.remove('hidden');if(unsubscribe){unsubscribe();unsubscribe=null}}});
function listen(user){if(unsubscribe)unsubscribe();const q=query(ref(db,'messages'),orderByChild('time'));unsubscribe=onValue(q,snap=>{const box=$('messages');box.innerHTML='';const data=snap.val()||{};const arr=Object.entries(data).sort((a,b)=>(a[1].time||0)-(b[1].time||0));if(!arr.length){box.innerHTML='<div class="empty">Todavía no hay mensajes ❤️</div>';return}for(const [id,m] of arr){const d=document.createElement('div');d.className='bubble'+(m.uid===user.uid?' mine':'');d.textContent=m.text||'';const t=document.createElement('span');t.className='time';t.textContent=m.time?new Date(m.time).toLocaleString('es-UY',{hour:'2-digit',minute:'2-digit'}):'...';d.appendChild(t);box.appendChild(d)}box.scrollTop=box.scrollHeight},e=>{boxError(e)});}
function boxError(e){$('messages').innerHTML='<div class="empty">No se pueden cargar los mensajes.<br><small>'+friendly(e)+'</small></div>'}
$('sendForm').onsubmit=async ev=>{ev.preventDefault();const input=$('messageInput'),text=input.value.trim();if(!text||!auth.currentUser)return;try{await push(ref(db,'messages'),{uid:auth.currentUser.uid,text,time:serverTimestamp()});input.value='';}catch(e){alert(friendly(e))}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
